---
Configuration:
    number: 23
    myStr: toto

Titre: "BANC DE TEST AGIV "


# ------ Relay values --------
# Corespondance Bits AGIV vs relay              
#       b8      b7      b6      b5      b4      b3      b2      b1      b0
#       nc      nc      Rr-     Rr+     Pwr     Rb-     Ra-     Rb+     Ra+           
# V+ connections:   A=x00,  B=x01,  C=x02,  D=x03
# V- connections:   A=x00,  B=x04,  C=x08,  D=x0C
# V- to Pwr: x10
# R hom +: x20
# R hom -: x40
# 


Commands:
    aoip_mes: 'MEAS2?'
    aoip_out: 'Sour{}'
    aoip_meas_time: 1.0      # Waiting time between source setting and Aoip measure
    giv_mes: 'IN:VAL?'
    giv_out: 'OUT:VAL{}'
    giv_meas_time: 0.5  # Time to stabilize input value on the giv
    aoip_range_sel_time: 2.0    # waiting time between range change and the reply of Aoip 

Ranges:
    "Choisisez la gamme":
        active: False

    "Allume la Led":
        active: True
        relays: [0x80] 
        aoip: "SENSE2:FUNC CURRENT;CURRENT:RANGE 25MA;SUPPLY OFF"
        giv4: ":MODE OUTPUT_CURRENT_020MA"
        measure_on: aoip    # The giv is on output mode, the measure is on AOIP
        correction: "GIV4 GAIN, OFFSET"
        points: [0.0]
        tolerance: 0.1

    "Sortie courant 0-20 mA":
        active: True
        calibrate: True  
        relays: [0x04]  # V+:A, V-:B
        aoip: "SENSE2:FUNC CURRENT;CURRENT:RANGE 25MA;SUPPLY OFF"
        giv4: ":MODE OUTPUT_CURRENT_020MA"
        measure_on: aoip    # The giv is on output mode, the measure is on AOIP
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 140.0]
        points: [0.0, 2.0, 4.0, 8.0, 10.0, 12.0, 16.0, 18.0, 20.0]
        tolerance: [0.05, 0.001]  # 0.05% +/-0.0

    "Sortie courant 4-20 mA":
        active: True
        calibrate: False  
        relays: [0x04]     # V+:A, V-:B
        aoip: "SENSE2:FUNC CURRENT;CURRENT:RANGE 25MA;SUPPLY OFF"
        giv4: ":MODE INPUT_CURRENT_420MA"
        measure_on: aoip 
        points: [4.0, 8.0, 10.0, 12.0, 16.0, 18.0, 20.0]
        tolerance: [0.05, 0.001]  # 0.05% +/-0.0

    "Sortie courant 0-20 mA passive":
        active: True
        calibrate: False  
        relays: [0x03, 0x04, 0x10]     # V+:D, V-:B, Pwr
        aoip: "SENSE2:FUNC CURRENT;CURRENT:RANGE 0MA;SUPPLY ON" # SUPPLY ON accepted only for 0mA and 4mA range
        aoip2: "SENSE2:FUNC CURRENT;CURRENT:RANGE 25MA"      # We could go to 25mA range with the suply keep to on after 0mA range
        giv4: ":MODE OUTPUT_CURRENT_020MA"
        measure_on: aoip    # The giv is on output mode, the measure is on AOIP
        points: [0.0, 2.0, 4.0, 8.0, 10.0, 12.0, 16.0, 18.0, 20.0]
        tolerance: [0.05, 0.001]  # 0.05% +/-0.0

    "Sortie courant 4-20 mA passive":
        active: True
        calibrate: False    # Calibré avec l'echelle 0..20mA
        relays: [0x03, 0x04, 0x10]     # V+:D, V-:B, Pwr
        aoip: "SENSE2:FUNC CURRENT;CURRENT:RANGE 0MA;SUPPLY ON"
        aoip2: "SENSE2:FUNC CURRENT;CURRENT:RANGE 25MA"      # We could go to 25mA range with the suply keep to on after 0mA range
        giv4: ":MODE OUTPUT_CURRENT_420MA"
        measure_on: aoip 
        points: [4.0, 8.0, 10.0, 12.0, 16.0, 18.0, 20.0]
        tolerance: [0.05, 0.001]  # 0.05% +/-0.0


    "Sortie tension 0..100mV":
        active: True
        calibrate: True
        relays: [0x02, 0x0C]     # V+:C, V-:D
        aoip: ":SENSE2:FUNC VOLT;VOLT:RANGE 100mV"
        giv4: ":OUTPUT_VOLTAGE_0100MV"
        measure_on: aoip 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 140.0]
        points: [-40.0, 0.0, 10.0, 20.0, 40.0, 80.0, 100.0, 140.0]
        tolerance: [0.05, 0.001]  # 0.05% +/-1µV

    "Sortie tension 0..10V":
        active: True
        calibrate: True
        relays: [0x02, 0x0C]     # V+:C, V-:D
        aoip: ":SENSE2:FUNC VOLT;VOLT:RANGE 50V"
        giv4: ":OUTPUT_VOLTAGE_010V"
        measure_on: aoip 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.2, 15.0]
        points: [0.0, 2.0, 4.0, 6.0, 8.0, 10.0]
        tolerance: [0.05, 0.1]  # 0.05% +/-1mV

    "Sortie resistance (+) 0.. 450R":
        active: True
        calibrate: True
        relays: [0x01, 0x08, 0x20]     # V+:B, V-:C Rhom+
        aoip: ":SENSE2:FUNC RES;RES:AUTO ON"
        giv4: ":OUTPUT_RESISTOR_0400OHMS"
        measure_on: aoip 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 450.0]
        points: [0.0, 0.1, 1.0, 80.0, 160.0, 240.0, 320.0, 450.0]
        tolerance: [0.05, 0.03]  # Il faut aussi passer 0.05%

    "Sortie resistance (-) 0.. 450R":
        active: True
        calibrate: True
        relays: [0x02, 0x04, 0x40]     # V+:C, V-:B Rhom-
        aoip: ":SENSE2:FUNC RES;RES:AUTO ON"
        giv4: ":OUTPUT_RESISTOR_0400OHMS"
        measure_on: aoip 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 450.0]
        points: [0.0, 0.1, 1.0, 80.0, 160.0, 240.0, 320.0, 450.0]
        tolerance: [0.05, 0.03]  #  0.05% +/- 0.03R

    "Sortie resistance (+) 0.. 4500R":
        active: True
        calibrate: True
        relays: [0x01, 0x08, 0x20]     # V+:B, V-:C Rhom+
        aoip: ":SENSE2:FUNC RES;RES:AUTO ON"
        giv4: ":OUTPUT_RESISTOR_04KOHMS"
        measure_on: aoip 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 4500.0]
        points: [0.0, 1.0, 10.0, 800.0, 1600.0, 2400.0, 3200.0, 4500.0]
        tolerance: [0.05, 0.03]  # Il faut aussi passer 0.05%

    "Sortie resistance (-) 0.. 4500R":
        active: True
        calibrate: True
        relays: [0x02, 0x04, 0x40]     # V+:C, V-:B Rhom-
        aoip: ":SENSE2:FUNC RES:AUTO ON"
        giv4: ":OUTPUT_RESISTOR_04KOHMS"
        measure_on: aoip 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 4500.0]
        points: [0.0, 1.0, 10.0, 800.0, 1600.0, 2400.0, 3200.0, 4500.0]
        tolerance: [0.05, 0.03]  #  0.05% +/- 0.03R


    "Mesure de tension 0..30V":
        active: True
        calibrate: True
        relays: [0x0, 0x0C]     # V+:A, V-:D
        aoip: ":sour:volt:range 50V;:sour:volt 1"
        giv4: ":INPUT_VOLTAGE_030V"
        measure_on: giv 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 30.0]
        points: [0.1, 1.0, 8.0, 10.0, 12.0, 16.0, 20.0, 31.0]
        tolerance: [0.1, 0.01]  # 0.1%, +/-10mV

    "Mesure de courrant 0-20 mA Pwr externe":  # Le CALYS ne sait pas coupper la source pour ce cas
        active: True
        relays: [0x01,0x0C,0x10] # V+:B,  V-:D, Pwr 
        aoip: ":sour:func curr"   
        aoip_out: 'Sour:current {}mA'      # More priority than general command
        giv4: ":INPUT_CURRENT_020MA"
        measure_on: giv 
        correction: "GIV4 GAIN, OFFSET"
        calibration_points: [0.0, 22.0]
        points: [0.0, 2.0, 4.0, 8.0, 10.0, 12.0, 16.0, 18.0, 20.0]
        tolerance: [0.05,0.001]  # 0.05% +/-1µA

    "Mesure de courrant 0-20 mA Pwr interne":  # Le CALYS ne sait pas coupper la source pour ce cas
        active: False   # Pas possible, on ne fait pas
        relays: [0x00,0x0C,0x10] # V+:A,  V-:B, Pwr 
        aoip: ":sour:func curr"   
        aoip_out: 'Sour:current {}mA'      # More priority than general command
        giv4: ":INPUT_CURRENT_020MA"
        measure_on: giv 
        correction: "GIV4 GAIN, OFFSET"
        points: [4.0, 8.0, 10.0, 12.0, 16.0, 18.0, 20.0]
        tolerance: [0.05,0.001]  # 0.05% +/-1µA
