# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1003, 884)
        font = QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_Titre = QLabel(self.centralwidget)
        self.label_Titre.setObjectName(u"label_Titre")
        self.label_Titre.setGeometry(QRect(96, 10, 631, 51))
        font1 = QFont()
        font1.setPointSize(20)
        self.label_Titre.setFont(font1)
        self.label_Titre.setScaledContents(False)
        self.label_Titre.setAlignment(Qt.AlignCenter)
        self.QTextConsole = QTextEdit(self.centralwidget)
        self.QTextConsole.setObjectName(u"QTextConsole")
        self.QTextConsole.setGeometry(QRect(20, 530, 911, 271))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(20, 50, 911, 441))
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.scrollCalibrate = QScrollArea(self.tab)
        self.scrollCalibrate.setObjectName(u"scrollCalibrate")
        self.scrollCalibrate.setGeometry(QRect(10, 30, 391, 341))
        self.scrollCalibrate.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 389, 339))
        self.scrollCalibrate.setWidget(self.scrollAreaWidgetContents)
        self.pBtRunCalibration = QPushButton(self.tab)
        self.pBtRunCalibration.setObjectName(u"pBtRunCalibration")
        self.pBtRunCalibration.setGeometry(QRect(570, 210, 181, 21))
        self.pBtSelectAll = QPushButton(self.tab)
        self.pBtSelectAll.setObjectName(u"pBtSelectAll")
        self.pBtSelectAll.setGeometry(QRect(570, 30, 181, 21))
        self.pBtUnselectAll = QPushButton(self.tab)
        self.pBtUnselectAll.setObjectName(u"pBtUnselectAll")
        self.pBtUnselectAll.setGeometry(QRect(570, 70, 181, 21))
        self.cBoxWriteCal = QCheckBox(self.tab)
        self.cBoxWriteCal.setObjectName(u"cBoxWriteCal")
        self.cBoxWriteCal.setGeometry(QRect(580, 110, 171, 21))
        self.cBoxWriteCal.setStyleSheet(u"")
        self.cBoxWriteCal.setChecked(True)
        self.cBoxRazCalib = QCheckBox(self.tab)
        self.cBoxRazCalib.setObjectName(u"cBoxRazCalib")
        self.cBoxRazCalib.setGeometry(QRect(580, 150, 181, 21))
        self.cBoxRazCalib.setChecked(True)
        self.pBtLockGiv = QPushButton(self.tab)
        self.pBtLockGiv.setObjectName(u"pBtLockGiv")
        self.pBtLockGiv.setEnabled(True)
        self.pBtLockGiv.setGeometry(QRect(570, 270, 181, 21))
        self.tabWidget.addTab(self.tab, "")
        self.Measures = QWidget()
        self.Measures.setObjectName(u"Measures")
        self.label_2 = QLabel(self.Measures)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 81, 21))
        font2 = QFont()
        font2.setPointSize(16)
        self.label_2.setFont(font2)
        self.scrollMeasures = QScrollArea(self.Measures)
        self.scrollMeasures.setObjectName(u"scrollMeasures")
        self.scrollMeasures.setGeometry(QRect(420, 40, 201, 341))
        self.scrollMeasures.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 199, 339))
        self.scrollMeasures.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollMeasRange = QScrollArea(self.Measures)
        self.scrollMeasRange.setObjectName(u"scrollMeasRange")
        self.scrollMeasRange.setGeometry(QRect(10, 40, 391, 341))
        self.scrollMeasRange.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 389, 339))
        self.scrollMeasRange.setWidget(self.scrollAreaWidgetContents_3)
        self.pBtSMeasSelectAll = QPushButton(self.Measures)
        self.pBtSMeasSelectAll.setObjectName(u"pBtSMeasSelectAll")
        self.pBtSMeasSelectAll.setGeometry(QRect(660, 40, 191, 21))
        self.pBtMeasUnselectAll = QPushButton(self.Measures)
        self.pBtMeasUnselectAll.setObjectName(u"pBtMeasUnselectAll")
        self.pBtMeasUnselectAll.setGeometry(QRect(660, 80, 191, 21))
        self.pBtRunMeasures = QPushButton(self.Measures)
        self.pBtRunMeasures.setObjectName(u"pBtRunMeasures")
        self.pBtRunMeasures.setGeometry(QRect(660, 130, 191, 21))
        self.label_5 = QLabel(self.Measures)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(420, 10, 81, 21))
        self.label_5.setFont(font2)
        self.tabWidget.addTab(self.Measures, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pBtSendAoip = QPushButton(self.tab_2)
        self.pBtSendAoip.setObjectName(u"pBtSendAoip")
        self.pBtSendAoip.setGeometry(QRect(150, 40, 71, 21))
        font3 = QFont()
        font3.setPointSize(10)
        self.pBtSendAoip.setFont(font3)
        self.pBtSendRly = QPushButton(self.tab_2)
        self.pBtSendRly.setObjectName(u"pBtSendRly")
        self.pBtSendRly.setGeometry(QRect(60, 40, 71, 21))
        self.cBoxDbgSendCmd = QComboBox(self.tab_2)
        self.cBoxDbgSendCmd.addItem("")
        self.cBoxDbgSendCmd.setObjectName(u"cBoxDbgSendCmd")
        self.cBoxDbgSendCmd.setGeometry(QRect(60, 100, 671, 31))
        self.cBoxDbgSendCmd.setEditable(True)
        self.pBtSendGiv = QPushButton(self.tab_2)
        self.pBtSendGiv.setObjectName(u"pBtSendGiv")
        self.pBtSendGiv.setGeometry(QRect(240, 40, 81, 21))
        self.pBtSendGiv.setFont(font3)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(60, 70, 181, 21))
        self.cBoxMultithread = QCheckBox(self.tab_2)
        self.cBoxMultithread.setObjectName(u"cBoxMultithread")
        self.cBoxMultithread.setGeometry(QRect(540, 40, 111, 21))
        self.cBoxMultithread.setChecked(True)
        self.cBoxAdvanced = QCheckBox(self.tab_2)
        self.cBoxAdvanced.setObjectName(u"cBoxAdvanced")
        self.cBoxAdvanced.setGeometry(QRect(380, 40, 131, 21))
        self.cBoxAdvanced.setChecked(True)
        self.comboRangeSelection = QComboBox(self.tab_2)
        self.comboRangeSelection.setObjectName(u"comboRangeSelection")
        self.comboRangeSelection.setGeometry(QRect(140, 250, 421, 41))
        self.comboRangeSelection.setFont(font)
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 500, 151, 21))
        self.label.setFont(font)
        self.lEIdentifiant = QLineEdit(self.centralwidget)
        self.lEIdentifiant.setObjectName(u"lEIdentifiant")
        self.lEIdentifiant.setGeometry(QRect(390, 500, 201, 21))
        self.lEIdentifiant.setFont(font)
        self.lEIdentifiant.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(300, 500, 81, 20))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(660, 500, 141, 20))
        self.label_4.setFont(font)
        self.lE_DateCalib = QLineEdit(self.centralwidget)
        self.lE_DateCalib.setObjectName(u"lE_DateCalib")
        self.lE_DateCalib.setGeometry(QRect(810, 500, 111, 21))
        self.lE_DateCalib.setFont(font)
        self.lE_DateCalib.setAlignment(Qt.AlignCenter)
        self.lE_DateCalib.setReadOnly(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1003, 27))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_Titre.setText(QCoreApplication.translate("MainWindow", u"AGIV Bench", None))
#if QT_CONFIG(tooltip)
        self.pBtRunCalibration.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Lancer le contr\u00f4le o\u00f9 la calibration des gammes s\u00e9l\u00e9ctionn\u00e9es.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pBtRunCalibration.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pBtRunCalibration.setText(QCoreApplication.translate("MainWindow", u"LANCER SELECTION", None))
#if QT_CONFIG(tooltip)
        self.pBtSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Selectionner toutes les gammes pour calibrer.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtSelectAll.setText(QCoreApplication.translate("MainWindow", u"SELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.pBtUnselectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>D\u00e9selectionner toutes les gammes. Utile pour revenir sur une gamme en particulier.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtUnselectAll.setText(QCoreApplication.translate("MainWindow", u"DESELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.cBoxWriteCal.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>A laisser coch\u00e9e par d\u00e9faut: Si cette case n'est pas coch\u00e9e, on contr\u00f4le juste les points de calibration. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxWriteCal.setText(QCoreApplication.translate("MainWindow", u"Modifier calibration", None))
#if QT_CONFIG(tooltip)
        self.cBoxRazCalib.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Si coch\u00e9, on \u00e9crase les calibrations pr\u00e9c\u00e9dentes en imposant un gain= 1 et offset \u00e0 0 avant la calibration. m\u00e9thode plus lente mais plus sure. Si d\u00e9coch\u00e9, on r\u00e9-ajuste la calibration a partir de celle existante. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxRazCalib.setText(QCoreApplication.translate("MainWindow", u"Forcer Z=0 G=1", None))
#if QT_CONFIG(tooltip)
        self.pBtLockGiv.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Permet de verouiller le GIV apr\u00e8s calibration. L'acc\u00e8s \u00e0 ce bouton n'est possible qu'apr\u00e8s que tous les gammes soient calibr\u00e9es.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtLockGiv.setText(QCoreApplication.translate("MainWindow", u"VERROUILLER GIV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Etalonnage", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Gamme", None))
#if QT_CONFIG(tooltip)
        self.pBtSMeasSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Selectionner toutes les gammes pour calibrer.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtSMeasSelectAll.setText(QCoreApplication.translate("MainWindow", u"SELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.pBtMeasUnselectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>D\u00e9selectionner toutes les gammes. Utile pour revenir sur une gamme en particulier.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtMeasUnselectAll.setText(QCoreApplication.translate("MainWindow", u"DESELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.pBtRunMeasures.setToolTip(QCoreApplication.translate("MainWindow", u"Lancer ou arreter les relev\u00e9s des gammes s\u00e9lectionn\u00e9es", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pBtRunMeasures.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pBtRunMeasures.setText(QCoreApplication.translate("MainWindow", u"LANCER SELECTION", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Mesures", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Measures), QCoreApplication.translate("MainWindow", u"Relev\u00e9s", None))
        self.pBtSendAoip.setText(QCoreApplication.translate("MainWindow", u"AOIP", None))
        self.pBtSendRly.setText(QCoreApplication.translate("MainWindow", u"Relais", None))
        self.cBoxDbgSendCmd.setItemText(0, QCoreApplication.translate("MainWindow", u"*SYS:ERR?", None))

        self.pBtSendGiv.setText(QCoreApplication.translate("MainWindow", u"GIV4", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Send Debug command", None))
        self.cBoxMultithread.setText(QCoreApplication.translate("MainWindow", u"Mutithread", None))
        self.cBoxAdvanced.setText(QCoreApplication.translate("MainWindow", u"Mode avanc\u00e9", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Debug", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Communications", None))
#if QT_CONFIG(whatsthis)
        self.lEIdentifiant.setWhatsThis(QCoreApplication.translate("MainWindow", u"Identifiant unique lu dans le GIV. Cet identifiant est le nom du fichier de \"Log\" cr\u00e9\u00e9 pour tracer les r\u00e9glages r\u00e9alis\u00e9s", None))
#endif // QT_CONFIG(whatsthis)
        self.lEIdentifiant.setText(QCoreApplication.translate("MainWindow", u"GIV4", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Identifiant</p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Dernier \u00e9talonnage:</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.lE_DateCalib.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Date du dernier \u00e9talonnage enregist\u00e9 dans le GIV4.</p><p>C'est la date du moment ou l'on d\u00e9clenche &quot;verouiller le GIV&quot;</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.lE_DateCalib.setText("")
    # retranslateUi

