---
Configuration:
    number: 23
    myStr: toto

Titre: "Configuration R450 avec PJ"

# Evolution du 19/11/2024: Adaptation tolérance R450 et PT100 à la fiche produit Rev. C
# (CR Réunion du 18/11/2024)


# ------ Relay values --------
# Corespondance Bits AGIV vs relay              
#       b8      b7      b6      b5      b4      b3      b2      b1      b0
#       nc      nc      Rr-     Rr+     Pwr     Rb-     Ra-     Rb+     Ra+           
# V+ connections:   A=x00,  B=x01,  C=x02,  D=x03
# V- connections:   A=x00,  B=x04,  C=x08,  D=x0C
# V- to Pwr: x10
# R hom +: x20
# R hom -: x40
# 

Options:
    advanced_tab: True   # Enable Adanced tab  panel
    advanced_box: False   # Enable Adanced cbox  panel
    reports_directory: 'z:\Agiv_reports'

Devices:
    scpi_relays: [',AGIV', 'color_cyan', 'avec le banc AGIV', 0.2, 115200]
    scpi_giv4:   [',GIV4', 'color_red_purple', 'avec le GIV4', 0.2, 115200]
    scpi_aoip:   [',PJ6301', 'color_bluepurple', 'avec le PJ', 2.0, 9600]

Commands:
    aoip_rem: '*CLS;REM;*ESR?'
    aoip_loc: '*CLS;LOC;*ESR?'
    aoip_mes: 'MEAS?'
    aoip_out: 'Sour {}'
    aoip_meas_time: 2.0      # Waiting time between source setting and Aoip measure
    giv_mes: 'IN:VAL?'
    giv_out: 'OUT:VAL {};:OUT:VAL?'
    giv_meas_time: 2.0  # Time to stabilize input value on the giv
    aoip_range_sel_time: 2.0    # waiting time between range change and the reply of Aoip 

Ranges:

    "Sortie resistance (+) 0.. 450R":
        active: True
        calibrate: True
        english_name: "Resistor simulator (+) 0..450R"
        relays: [0x01, 0x08, 0x20]     # V+:B, V-:C Rhom+
        aoip: "*CLS;RANGE_IN OHM600,WIRE4;*ESR?"
        giv4: ":MODE OUTPUT_RESISTOR_0400OHMS"
        measure_on: aoip 
        aoip_meas_time: 4.0 # Resistor is more slow
        correction: ":OUTput:RES:0400:POS:ADJ_DAC_"
        z_factor: 0.0    # For resistance, don't set Z
        z_g_overwrite: True     # For this range, force default values g=1 and z=0 before correction calculation
        calibration_points: [0.0, 450.0]
        points: [0.0, 0.1, 1.0, 80.0, 100.0, 160.0, 240.0, 320.0, 450.0]
        tolerance: [0.0, 0.15]  # +/-0.15 Ohms sur toutes l'échelle (fiche produit Rév C)
        full_scale: 450.0

    "Sortie resistance (-) 0.. 450R":
        active: True
        calibrate: True
        english_name: "Resistor simulator (-) 0..450R"
        relays: [0x02, 0x04, 0x40]     # V+:C, V-:B Rhom-
        aoip: "*CLS;RANGE_IN OHM600,WIRE4;*ESR?"
        giv4: ":MODE OUTPUT_RESISTOR_0400OHMS"
        set_val: ['Set',GIV4','*CLS; :OUT:VAL {v};:SYST:ERR?','No Error']  # Device where the reference is set, message to set, expected answer
        get_val: ['Get','PJ6301','MEAS?', '',6]          # Device where measure is get, message to get,  expected answer, wait time
        correction: ":OUTput:RES:0400:NEG:ADJ_DAC_"
        z_factor: 0.0    # For resistance, don't set Z
        z_g_overwrite: True     # For this range, force default values g=1 and z=0 before correction calculation
        calibration_points: [0.0, 450.0]
        points: [0.0, 0.1, 1.0, 80.0, 100.0, 160.0, 240.0, 320.0, 450.0]
        tolerance: [0.0, 0.15]  # +/-0.15 Ohms sur toutes l'échelle (fiche produit Rév C)
        full_scale: 450.0



    "Sortie Pt100 (+)":
        active: True
        calibrate: False
        english_name: "Output Pt100 (+)"
        relays: [0x01, 0x08, 0x20]     # V+:B, V-:C Rhom+
        aoip: "*CLS;RANGE_IN RT,WIRE4,TYP_PT100,CEL;*ESR?"
        giv4: "*CLS;:MODE OUTPUT_RTD_PT100;:SYST:ERR?" # Affiche en retour la valeur de compensation mesurée
        set_val: ['Set',GIV4','*CLS; :OUT:VAL {v};:SYST:ERR?','No Error']  # Device where the reference is set, message to set, expected answer
        get_val: ['Get','PJ6301','MEAS?', '',6]          # Device where measure is get, message to get,  expected answer, wait time
        correction: "None"  # Pas d'ajustage G/Z: Ce sont ceux des resistance
        calibration_points: [0, 0]
        points: [-200.0, -100.0, 0.0, +100.0, +200.0, 400.0]
        tolerance: [0.00, 0.4]  # On tolere une différece de +/-0.4° 
        full_scale: 1050.0


    "Sortie Pt100 (-)":
        active: True
        calibrate: False
        english_name: "Output Pt100 (-)"
        relays: [0x02, 0x04, 0x40]     # V+:C, V-:B Rhom-
        aoip: "*CLS;RANGE_IN RT,WIRE4,TYP_PT100,CEL;*ESR?"
        giv4: "*CLS;:MODE OUTPUT_RTD_PT100;:SYST:ERR?" # Affiche en retour la valeur de compensation mesurée
        set_val: ['Set',GIV4','*CLS; :OUT:VAL {v};:SYST:ERR?','No Error']  # Device where the reference is set, message to set, expected answer
        get_val: ['Get','PJ6301','MEAS?', '',6]          # Device where measure is get, message to get,  expected answer, wait time
        correction: "None"  # Pas d'ajustage G/Z: Ce sont ceux des resistance
        calibration_points: [0, 0]
        points: [-200.0, -100.0, 0.0, +100.0, +200.0, 400.0]
        tolerance: [0.00, 0.4]  # On tolere une différece de +/-0.4° 
        full_scale: 1050.0
