# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1003, 672)
        font = QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_Titre = QLabel(self.centralwidget)
        self.label_Titre.setObjectName(u"label_Titre")
        self.label_Titre.setGeometry(QRect(110, 0, 761, 31))
        font1 = QFont()
        font1.setPointSize(20)
        self.label_Titre.setFont(font1)
        self.label_Titre.setScaledContents(False)
        self.label_Titre.setAlignment(Qt.AlignCenter)
        self.QTextConsole = QTextEdit(self.centralwidget)
        self.QTextConsole.setObjectName(u"QTextConsole")
        self.QTextConsole.setGeometry(QRect(30, 480, 911, 131))
        self.QTextConsole.setAcceptDrops(False)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(30, 30, 911, 411))
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.scrollCalibrate = QScrollArea(self.tab)
        self.scrollCalibrate.setObjectName(u"scrollCalibrate")
        self.scrollCalibrate.setGeometry(QRect(10, 0, 391, 371))
        self.scrollCalibrate.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 389, 369))
        self.scrollCalibrate.setWidget(self.scrollAreaWidgetContents)
        self.pBtRunCalibration = QPushButton(self.tab)
        self.pBtRunCalibration.setObjectName(u"pBtRunCalibration")
        self.pBtRunCalibration.setGeometry(QRect(570, 120, 181, 21))
        self.pBtSelectAll = QPushButton(self.tab)
        self.pBtSelectAll.setObjectName(u"pBtSelectAll")
        self.pBtSelectAll.setGeometry(QRect(570, 30, 181, 21))
        self.pBtUnselectAll = QPushButton(self.tab)
        self.pBtUnselectAll.setObjectName(u"pBtUnselectAll")
        self.pBtUnselectAll.setGeometry(QRect(570, 70, 181, 21))
        self.cBoxWriteCal = QCheckBox(self.tab)
        self.cBoxWriteCal.setObjectName(u"cBoxWriteCal")
        self.cBoxWriteCal.setGeometry(QRect(570, 270, 171, 21))
        self.cBoxWriteCal.setStyleSheet(u"")
        self.cBoxWriteCal.setChecked(True)
        self.cBoxRazCalib = QCheckBox(self.tab)
        self.cBoxRazCalib.setObjectName(u"cBoxRazCalib")
        self.cBoxRazCalib.setGeometry(QRect(570, 300, 181, 21))
        self.cBoxRazCalib.setChecked(False)
        self.pBtLockGiv = QPushButton(self.tab)
        self.pBtLockGiv.setObjectName(u"pBtLockGiv")
        self.pBtLockGiv.setEnabled(True)
        self.pBtLockGiv.setGeometry(QRect(570, 170, 181, 21))
        self.cBoxRunMeasures = QCheckBox(self.tab)
        self.cBoxRunMeasures.setObjectName(u"cBoxRunMeasures")
        self.cBoxRunMeasures.setGeometry(QRect(570, 330, 241, 21))
        self.cBoxRunMeasures.setChecked(True)
        self.tabWidget.addTab(self.tab, "")
        self.Measures = QWidget()
        self.Measures.setObjectName(u"Measures")
        self.label_2 = QLabel(self.Measures)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 0, 81, 21))
        font2 = QFont()
        font2.setPointSize(16)
        self.label_2.setFont(font2)
        self.scrollMeasures = QScrollArea(self.Measures)
        self.scrollMeasures.setObjectName(u"scrollMeasures")
        self.scrollMeasures.setGeometry(QRect(420, 30, 201, 341))
        self.scrollMeasures.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 199, 339))
        self.scrollMeasures.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollMeasRange = QScrollArea(self.Measures)
        self.scrollMeasRange.setObjectName(u"scrollMeasRange")
        self.scrollMeasRange.setGeometry(QRect(10, 30, 391, 341))
        self.scrollMeasRange.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 389, 339))
        self.scrollMeasRange.setWidget(self.scrollAreaWidgetContents_3)
        self.pBtSMeasSelectAll = QPushButton(self.Measures)
        self.pBtSMeasSelectAll.setObjectName(u"pBtSMeasSelectAll")
        self.pBtSMeasSelectAll.setGeometry(QRect(660, 40, 191, 21))
        self.pBtMeasUnselectAll = QPushButton(self.Measures)
        self.pBtMeasUnselectAll.setObjectName(u"pBtMeasUnselectAll")
        self.pBtMeasUnselectAll.setGeometry(QRect(660, 80, 191, 21))
        self.pBtRunMeasures = QPushButton(self.Measures)
        self.pBtRunMeasures.setObjectName(u"pBtRunMeasures")
        self.pBtRunMeasures.setGeometry(QRect(660, 130, 191, 21))
        self.label_5 = QLabel(self.Measures)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(420, 0, 81, 21))
        self.label_5.setFont(font2)
        self.pBtGenerateRepport = QPushButton(self.Measures)
        self.pBtGenerateRepport.setObjectName(u"pBtGenerateRepport")
        self.pBtGenerateRepport.setGeometry(QRect(660, 180, 191, 21))
        self.cBoxLastDate = QCheckBox(self.Measures)
        self.cBoxLastDate.setObjectName(u"cBoxLastDate")
        self.cBoxLastDate.setGeometry(QRect(660, 220, 191, 21))
        self.cBoxLastDate.setStyleSheet(u"")
        self.cBoxLastDate.setChecked(True)
        self.cBoxLastSequence = QCheckBox(self.Measures)
        self.cBoxLastSequence.setObjectName(u"cBoxLastSequence")
        self.cBoxLastSequence.setGeometry(QRect(660, 250, 191, 21))
        self.cBoxLastSequence.setStyleSheet(u"")
        self.cBoxLastSequence.setChecked(True)
        self.pBtGenerateAllGIVs = QPushButton(self.Measures)
        self.pBtGenerateAllGIVs.setObjectName(u"pBtGenerateAllGIVs")
        self.pBtGenerateAllGIVs.setGeometry(QRect(660, 290, 191, 21))
        self.tabWidget.addTab(self.Measures, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pBtSendAoip = QPushButton(self.tab_2)
        self.pBtSendAoip.setObjectName(u"pBtSendAoip")
        self.pBtSendAoip.setGeometry(QRect(150, 40, 71, 21))
        font3 = QFont()
        font3.setPointSize(10)
        self.pBtSendAoip.setFont(font3)
        self.pBtSendRly = QPushButton(self.tab_2)
        self.pBtSendRly.setObjectName(u"pBtSendRly")
        self.pBtSendRly.setGeometry(QRect(60, 40, 71, 21))
        self.cBoxDbgSendCmd = QComboBox(self.tab_2)
        self.cBoxDbgSendCmd.addItem("")
        self.cBoxDbgSendCmd.setObjectName(u"cBoxDbgSendCmd")
        self.cBoxDbgSendCmd.setGeometry(QRect(60, 100, 671, 31))
        self.cBoxDbgSendCmd.setEditable(True)
        self.pBtSendGiv = QPushButton(self.tab_2)
        self.pBtSendGiv.setObjectName(u"pBtSendGiv")
        self.pBtSendGiv.setGeometry(QRect(240, 40, 81, 21))
        self.pBtSendGiv.setFont(font3)
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(60, 70, 181, 21))
        self.cBoxMultithread = QCheckBox(self.tab_2)
        self.cBoxMultithread.setObjectName(u"cBoxMultithread")
        self.cBoxMultithread.setGeometry(QRect(540, 40, 111, 21))
        self.cBoxMultithread.setChecked(True)
        self.cBoxAdvanced = QCheckBox(self.tab_2)
        self.cBoxAdvanced.setObjectName(u"cBoxAdvanced")
        self.cBoxAdvanced.setGeometry(QRect(380, 40, 131, 21))
        self.cBoxAdvanced.setChecked(True)
        self.pBtAdvLockGiv = QPushButton(self.tab_2)
        self.pBtAdvLockGiv.setObjectName(u"pBtAdvLockGiv")
        self.pBtAdvLockGiv.setGeometry(QRect(760, 60, 121, 21))
        self.pBtAdvUnlockGiv = QPushButton(self.tab_2)
        self.pBtAdvUnlockGiv.setObjectName(u"pBtAdvUnlockGiv")
        self.pBtAdvUnlockGiv.setGeometry(QRect(760, 100, 121, 21))
        self.tabWidget.addTab(self.tab_2, "")
        self.lbl_Comm = QLabel(self.centralwidget)
        self.lbl_Comm.setObjectName(u"lbl_Comm")
        self.lbl_Comm.setGeometry(QRect(30, 450, 151, 21))
        self.lbl_Comm.setFont(font)
        self.lEIdentifiant = QLineEdit(self.centralwidget)
        self.lEIdentifiant.setObjectName(u"lEIdentifiant")
        self.lEIdentifiant.setGeometry(QRect(440, 450, 161, 21))
        self.lEIdentifiant.setFont(font)
        self.lEIdentifiant.setAlignment(Qt.AlignCenter)
        self.lbl_Identifiant = QLabel(self.centralwidget)
        self.lbl_Identifiant.setObjectName(u"lbl_Identifiant")
        self.lbl_Identifiant.setGeometry(QRect(310, 450, 121, 20))
        self.lbl_Identifiant.setFont(font)
        self.lbl_LastEtal = QLabel(self.centralwidget)
        self.lbl_LastEtal.setObjectName(u"lbl_LastEtal")
        self.lbl_LastEtal.setGeometry(QRect(670, 450, 141, 20))
        self.lbl_LastEtal.setFont(font)
        self.lE_DateCalib = QLineEdit(self.centralwidget)
        self.lE_DateCalib.setObjectName(u"lE_DateCalib")
        self.lE_DateCalib.setGeometry(QRect(820, 450, 111, 21))
        self.lE_DateCalib.setFont(font)
        self.lE_DateCalib.setAlignment(Qt.AlignCenter)
        self.lE_DateCalib.setReadOnly(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.tabWidget.raise_()
        self.lbl_Comm.raise_()
        self.lEIdentifiant.raise_()
        self.lbl_Identifiant.raise_()
        self.lbl_LastEtal.raise_()
        self.lE_DateCalib.raise_()
        self.label_Titre.raise_()
        self.QTextConsole.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1003, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_Titre.setText(QCoreApplication.translate("MainWindow", u"AGIV Bench", None))
#if QT_CONFIG(tooltip)
        self.pBtRunCalibration.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Lancer le contr\u00f4le ou la calibration des gammes s\u00e9l\u00e9ctionn\u00e9es.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pBtRunCalibration.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pBtRunCalibration.setText(QCoreApplication.translate("MainWindow", u"LANCER AJUSTAGE", None))
#if QT_CONFIG(tooltip)
        self.pBtSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Selectionner toutes les gammes pour calibrer.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtSelectAll.setText(QCoreApplication.translate("MainWindow", u"SELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.pBtUnselectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>D\u00e9selectionner toutes les gammes. Utile pour revenir sur une gamme en particulier.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtUnselectAll.setText(QCoreApplication.translate("MainWindow", u"DESELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.cBoxWriteCal.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>A laisser coch\u00e9e par d\u00e9faut: Si cette case n'est pas coch\u00e9e, on contr\u00f4le juste les points de calibration. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxWriteCal.setText(QCoreApplication.translate("MainWindow", u"Modifier ajustage", None))
#if QT_CONFIG(tooltip)
        self.cBoxRazCalib.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Si coch\u00e9, on \u00e9crase les calibrations pr\u00e9c\u00e9dentes en imposant un gain= 1 et offset \u00e0 0 avant la calibration. m\u00e9thode plus lente mais plus sure. Si d\u00e9coch\u00e9, on r\u00e9-ajuste la calibration a partir de celle existante. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxRazCalib.setText(QCoreApplication.translate("MainWindow", u"Forcer G=1", None))
#if QT_CONFIG(tooltip)
        self.pBtLockGiv.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Permet de verouiller le GIV apr\u00e8s calibration. L'acc\u00e8s \u00e0 ce bouton n'est possible qu'apr\u00e8s que tous les gammes soient calibr\u00e9es.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtLockGiv.setText(QCoreApplication.translate("MainWindow", u"VERROUILLER GIV", None))
#if QT_CONFIG(tooltip)
        self.cBoxRunMeasures.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Si coch\u00e9, on lance automatiquement un relev\u00e9 de mesures apr\u00e8s la fin de l'ajustage. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxRunMeasures.setText(QCoreApplication.translate("MainWindow", u"Lancer un relev\u00e9 apr\u00e8s ajustage", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Ajustage", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Gamme", None))
#if QT_CONFIG(tooltip)
        self.pBtSMeasSelectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Selectionner toutes les gammes pour calibrer.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtSMeasSelectAll.setText(QCoreApplication.translate("MainWindow", u"SELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.pBtMeasUnselectAll.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>D\u00e9selectionner toutes les gammes. Utile pour revenir sur une gamme en particulier.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pBtMeasUnselectAll.setText(QCoreApplication.translate("MainWindow", u"DESELECT TOUT", None))
#if QT_CONFIG(tooltip)
        self.pBtRunMeasures.setToolTip(QCoreApplication.translate("MainWindow", u"Lancer ou arreter les relev\u00e9s des gammes s\u00e9lectionn\u00e9es", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pBtRunMeasures.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pBtRunMeasures.setText(QCoreApplication.translate("MainWindow", u"LANCER MESURES", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Mesures", None))
#if QT_CONFIG(tooltip)
        self.pBtGenerateRepport.setToolTip(QCoreApplication.translate("MainWindow", u"G\u00e9n\u00e9rer fichier excel des mesures r\u00e9alis\u00e9es", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pBtGenerateRepport.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pBtGenerateRepport.setText(QCoreApplication.translate("MainWindow", u"GENERER RAPPORT GIV", None))
#if QT_CONFIG(tooltip)
        self.cBoxLastDate.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Si coch\u00e9e, tous les relev\u00e9s connus du Giv sont pr\u00e9sent dans le rapport, avec un onglet pour chaque date. Si d\u00e9coch\u00e9e, on n'affichera que la derni\u00e8re date de relev\u00e9s.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxLastDate.setText(QCoreApplication.translate("MainWindow", u"Toutes les dates", None))
#if QT_CONFIG(tooltip)
        self.cBoxLastSequence.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Si coch\u00e9e, toutes les mesures obtenues apr\u00e8s un &quot;Lancer mesures&quot; apparaissent. Si d\u00e9coch\u00e9e, on affiche que les dernieres mesures d'une journ\u00e9e.  .</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.cBoxLastSequence.setText(QCoreApplication.translate("MainWindow", u"Toutes les mesures", None))
#if QT_CONFIG(tooltip)
        self.pBtGenerateAllGIVs.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>G\u00e9n\u00e9rer un fichier excel des mesures les plus r\u00e9centes de chaque GIV pour comparaison.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pBtGenerateAllGIVs.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pBtGenerateAllGIVs.setText(QCoreApplication.translate("MainWindow", u"GEN. COMPARATIF GIVS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Measures), QCoreApplication.translate("MainWindow", u"Relev\u00e9s", None))
        self.pBtSendAoip.setText(QCoreApplication.translate("MainWindow", u"AOIP", None))
        self.pBtSendRly.setText(QCoreApplication.translate("MainWindow", u"Relais", None))
        self.cBoxDbgSendCmd.setItemText(0, QCoreApplication.translate("MainWindow", u"*SYS:ERR?", None))

        self.pBtSendGiv.setText(QCoreApplication.translate("MainWindow", u"GIV4", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Send Debug command", None))
        self.cBoxMultithread.setText(QCoreApplication.translate("MainWindow", u"Mutithread", None))
        self.cBoxAdvanced.setText(QCoreApplication.translate("MainWindow", u"Mode avanc\u00e9", None))
        self.pBtAdvLockGiv.setText(QCoreApplication.translate("MainWindow", u"LOCK GIV", None))
        self.pBtAdvUnlockGiv.setText(QCoreApplication.translate("MainWindow", u"UNLOCK GIV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Avanc\u00e9...", None))
        self.lbl_Comm.setText(QCoreApplication.translate("MainWindow", u"Communications", None))
#if QT_CONFIG(whatsthis)
        self.lEIdentifiant.setWhatsThis(QCoreApplication.translate("MainWindow", u"Identifiant unique lu dans le GIV. Cet identifiant est le nom du fichier de \"Log\" cr\u00e9\u00e9 pour tracer les r\u00e9glages r\u00e9alis\u00e9s", None))
#endif // QT_CONFIG(whatsthis)
        self.lEIdentifiant.setText(QCoreApplication.translate("MainWindow", u"GIV4", None))
        self.lbl_Identifiant.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Identifiant GIV4</p></body></html>", None))
        self.lbl_LastEtal.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Dernier \u00e9talonnage:</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.lE_DateCalib.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Date du dernier \u00e9talonnage enregist\u00e9 dans le GIV4.</p><p>C'est la date du moment ou l'on d\u00e9clenche &quot;verouiller le GIV&quot;</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.lE_DateCalib.setText("")
    # retranslateUi

